import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { ThemeProvider } from "next-themes";
import { Provider } from "react-redux";
import { store } from "@toolkit/store";
import localFont from "@next/font/local";
import { Roboto } from "@next/font/google";

const amagro = localFont({
  src: "../public/fonts/Amagro/Amagro.ttf",
  variable: "--font-amagro",
});

export const nanumMyeongjo = localFont({
  src: [
    {
      path: "../public/fonts/Nanum_Myeongjo/NanumMyeongjo-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Nanum_Myeongjo/NanumMyeongjo-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Nanum_Myeongjo/NanumMyeongjo-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  display: "fallback",
  style: "normal",
  fallback: ["system-ui"],
  variable: "--font-nanumMyeongjo",
});

export const notoSerifKR = localFont({
  src: [
    {
      path: "../public/fonts/Noto_Serif_KR/NotoSerifKR-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Noto_Serif_KR/NotoSerifKR-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Noto_Serif_KR/NotoSerifKR-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Noto_Serif_KR/NotoSerifKR-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Noto_Serif_KR/NotoSerifKR-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  display: "fallback",
  style: "normal",
  fallback: ["system-ui"],
  variable: "--font-notoSerifKR",
});

export const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "fallback",
  style: "normal",
  fallback: ["system-ui"],
  variable: "--font-roboto",
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>SAK Exhibition</title>
        <meta
          name="description"
          content="SAK Exhibition Generated by Kim Yoo"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
      </Head>

      <ThemeProvider attribute="class">
        <Provider store={store}>
          <main className={` ${amagro.variable} ${notoSerifKR.className}`}>
            <Component {...pageProps} />
          </main>
        </Provider>
      </ThemeProvider>
    </>
  );
}
